packages:
  - "packages/*"
  - "extensions/*"
  - "implementations/*"
  - "examples/*"
  - "examples/*/*"
  - "bin"
allowBuilds:
  '@google/genai': false
  esbuild: true
  msgpackr-extract: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false
